In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df_eco = pd.read_csv("economy.csv")
df_bus = pd.read_csv("business.csv")

In [3]:
df_bus.sample(6)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
67674,22-03-2022,Vistara,UK,708,20:25,Kolkata,23h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:15,Chennai,"55,983"
37802,25-03-2022,Air India,AI,660,18:00,Mumbai,25h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:00,Chennai,"49,613"
11542,18-03-2022,Vistara,UK,933,15:30,Delhi,18h 10m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:40,Kolkata,"65,529"
28116,20-02-2022,Vistara,UK,950,21:55,Mumbai,21h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:35,Kolkata,"62,045"
91190,27-03-2022,Air India,AI,545,19:10,Chennai,12h 55m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,08:05,Kolkata,"34,432"
59332,12-03-2022,Vistara,UK,706,10:15,Kolkata,11h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,21:15,Mumbai,"64,831"

In [4]:
df_eco.sample(6)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
146949,21-03-2022,Vistara,UK,776,17:35,Kolkata,27h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,572"
16252,14-03-2022,SpiceJet,SG,8938,17:45,Delhi,23h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,16:50,Bangalore,"3,569"
78517,21-02-2022,AirAsia,I5,1569,21:20,Mumbai,11h 10m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,08:30,Chennai,"5,939"
155307,07-03-2022,Air India,AI,525,06:00,Hyderabad,17h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:00,Delhi,"4,172"
133601,20-03-2022,GO FIRST,G8,789,10:00,Kolkata,13h 55m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"5,507"
61148,29-03-2022,Air India,AI,888,19:00,Mumbai,25h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:05,Bangalore,"6,502"

In [5]:
df_eco.shape , df_bus.shape

((206774, 11), (93487, 11))

In [6]:
df_bus.isnull().sum()

date          0
airline       0
ch_code       0
num_code      0
dep_time      0
from          0
time_taken    0
stop          0
arr_time      0
to            0
price         0
dtype: int64

In [7]:
df_eco.isnull().sum()

date          0
airline       0
ch_code       0
num_code      0
dep_time      0
from          0
time_taken    0
stop          0
arr_time      0
to            0
price         0
dtype: int64

In [8]:
df_eco.duplicated().sum()

np.int64(2)

In [9]:
df_bus.duplicated().sum()

np.int64(0)

In [10]:
df_eco.drop_duplicates(inplace=True)

In [11]:
df_bus['class'] = "business"

In [12]:
df_eco['class'] = "economy"

In [13]:
df = pd.concat([df_eco,df_bus])
df.shape

(300259, 12)

In [14]:
df.sample(8)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,class
76813,22-02-2022,Vistara,UK,890,17:40,Hyderabad,14h 55m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,08:35,Kolkata,"61,899",business
64369,28-02-2022,Air India,AI,424,13:30,Kolkata,21h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswa...,10:30,Hyderabad,"52,063",business
56222,12-03-2022,Air India,AI,765,18:55,Kolkata,24h 55m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Delhi,"48,079",business
105917,06-03-2022,Indigo,6E,524,10:45,Bangalore,07h 55m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,18:40,Kolkata,"6,092",economy
182092,24-02-2022,Indigo,6E,605,13:05,Chennai,07h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Delhi,"7,877",economy
32847,14-03-2022,Vistara,UK,951,14:20,Delhi,06h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"5,772",economy
104207,23-02-2022,AirAsia,I5,992,23:10,Bangalore,02h 25m,non-stop,01:35,Kolkata,"5,179",economy
147684,28-03-2022,Indigo,6E,566,21:55,Kolkata,08h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,05:55,Hyderabad,"2,436",economy

In [15]:
df['stop'] = df['stop'].str.replace("\n","")
df['stop'] = df['stop'].str.replace("\t","")

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 300259 entries, 0 to 93486
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        300259 non-null  str
 1   airline     300259 non-null  str
 2   ch_code     300259 non-null  str
 3   num_code    300259 non-null  int64
 4   dep_time    300259 non-null  str
 5   from        300259 non-null  str
 6   time_taken  300259 non-null  str
 7   stop        300259 non-null  str
 8   arr_time    300259 non-null  str
 9   to          300259 non-null  str
 10  price       300259 non-null  str
 11  class       300259 non-null  str
dtypes: int64(1), str(11)
memory usage: 50.1 MB

In [17]:
df['date']  = pd.to_datetime(df['date'],format="%d-%m-%Y")

In [18]:
df['from'].value_counts()

from
Delhi        61343
Mumbai       60903
Bangalore    52106
Kolkata      46347
Hyderabad    40860
Chennai      38700
Name: count, dtype: int64

In [19]:
df['to'].value_counts()

to
Mumbai       59107
Delhi        57361
Bangalore    51112
Kolkata      49535
Hyderabad    42776
Chennai      40368
Name: count, dtype: int64

In [20]:
df['stop'].value_counts()

stop
1-stop                      243601
non-stop                     36044
2+-stop                      13288
1-stopVia IXU                 1839
1-stopVia IDR                 1398
1-stopVia Patna                674
1-stopVia Indore               381
1-stopVia PAT                  354
1-stopVia MYQ                  321
1-stopVia Bhubaneswar          301
1-stopVia KLH                  284
1-stopVia JGB                  193
1-stopVia JRG                  175
1-stopVia STV                  169
1-stopVia BBI                  158
1-stopVia Delhi                153
1-stopVia Hyderabad            143
1-stopVia IXE                  120
1-stopVia Ranchi               114
1-stopVia Raipur               102
1-stopVia Chennai               77
1-stopVia Guwahati              55
1-stopVia Mysore                45
1-stopVia Mangalore             39
1-stopVia Mumbai                31
1-stopVia Kolkata               28
1-stopVia VTZ                   27
1-stopVia Nagpur                25
1-stopVia RPR                   22
1-stopVia NDC                   22
1-stopVia GOP                   16
1-stopVia Surat                 14
1-stopVia Lucknow               13
1-stopVia NAG                    9
1-stopVia Vishakhapatnam         8
1-stopVia Kolhapur               5
1-stopVia IXR                    4
1-stopVia GAY                    3
1-stopVia GAU                    3
1-stopVia HYD                    1
Name: count, dtype: int64

In [21]:
df['stop'] = df['stop'].str.split(" ").str[0]

In [22]:
df['stop'].value_counts()

stop
1-stop       243601
non-stop      36044
2+-stop       13288
1-stopVia      7326
Name: count, dtype: int64

In [23]:
df.sample(7)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,class
67806,2022-03-18,Indigo,6E,5392,17:30,Mumbai,05h 05m,1-stop,22:35,Kolkata,"5,595",economy
67405,2022-03-16,Air India,AI,806,08:00,Mumbai,11h 10m,1-stop,19:10,Kolkata,"4,977",economy
59368,2022-03-13,Air India,AI,402,10:25,Kolkata,11h 10m,1-stop,21:35,Mumbai,"50,271",business
30751,2022-03-24,Vistara,UK,988,20:55,Mumbai,21h 10m,1-stop,18:05,Kolkata,"62,045",business
52259,2022-03-29,Indigo,6E,5313,17:05,Mumbai,04h 55m,1-stop,22:00,Delhi,"2,339",economy
140557,2022-03-18,GO FIRST,G8,7562,12:30,Kolkata,07h 10m,1-stop,19:40,Bangalore,"6,109",economy
48566,2022-03-20,Air India,AI,503,17:50,Bangalore,15h 10m,1-stop,09:00,Kolkata,"60,508",business

In [24]:
df['airline'].value_counts()

airline
Vistara      127859
Air India     80892
Indigo        43120
GO FIRST      23177
AirAsia       16098
SpiceJet       9011
StarAir          61
Trujet           41
Name: count, dtype: int64

In [25]:
df['price'] = df['price'].str.replace(',','')
df['price'] = df['price'].astype(int)

In [26]:
df.columns

Index(['date', 'airline', 'ch_code', 'num_code', 'dep_time', 'from',
       'time_taken', 'stop', 'arr_time', 'to', 'price', 'class'],
      dtype='str')

In [27]:
df['ch_code'].nunique()

8

In [28]:
df['num_code'].nunique()

1255

In [29]:
df.drop(['ch_code','num_code'],axis=1,inplace=True)

In [30]:
df['time'] =  df['dep_time'].str.split(":").str[0].astype(int)

In [31]:
def time_of_day(x):
    if x >= 5 and x < 9:
        return "early morning"
    elif x >= 9 and x < 12:
        return "morning"
    elif x >= 12 and x < 16:
        return "afternoon"
    elif x >= 16 and x < 20:
        return "evening"
    else:
        return "night"
df['time_of_day'] = df['time'].apply(time_of_day)

In [32]:
df.drop(['time'],axis=1,inplace=True)

In [33]:
df['is_weekday'] = df['date'].dt.day_of_week
df['month'] = df['date'].dt.month

df['is_weekday'].value_counts()

is_weekday
0    44072
1    44041
2    44023
3    44022
6    42398
5    41809
4    39894
Name: count, dtype: int64

In [34]:
df["time_taken"].value_counts()

time_taken
02h 10m    4242
02h 15m    4036
02h 45m    2879
02h 05m    2755
02h 50m    2323
           ...
41h 05m       1
35h 40m       1
47h 05m       1
44h 30m       1
41h 30m       1
Name: count, Length: 483, dtype: int64

In [35]:
df['hrs'] = df['time_taken'].str.extract(r'(\d+)h').fillna(0).astype(int)
df['min'] = df['time_taken'].str.extract(r'(\d+)m').fillna(0).astype(int)

df['total_duration_mins'] = (df['hrs'] * 60) + df['min']

df.drop(['hrs', 'min','time_taken'],axis=1,inplace=True)

print(df['total_duration_mins'].describe())

count    300259.000000
mean        733.063339
std         431.573994
min          50.000000
25%         405.000000
50%         675.000000
75%         970.000000
max        2990.000000
Name: total_duration_mins, dtype: float64

In [36]:
df.drop(['dep_time','arr_time'],axis=1,inplace=True)

In [37]:
df.head()

,date,airline,from,stop,to,price,class,time_of_day,is_weekday,month,total_duration_mins
0,2022-02-11,SpiceJet,Delhi,non-stop,Mumbai,5953,economy,evening,4,2,130
1,2022-02-11,SpiceJet,Delhi,non-stop,Mumbai,5953,economy,early morning,4,2,140
2,2022-02-11,AirAsia,Delhi,non-stop,Mumbai,5956,economy,night,4,2,130
3,2022-02-11,Vistara,Delhi,non-stop,Mumbai,5955,economy,morning,4,2,135
4,2022-02-11,Vistara,Delhi,non-stop,Mumbai,5955,economy,early morning,4,2,140

In [38]:
df["date"].dt.year.unique()

array([2022], dtype=int32)

In [39]:
df.shape

(300259, 11)

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 300259 entries, 0 to 93486
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   date                 300259 non-null  datetime64[us]
 1   airline              300259 non-null  str
 2   from                 300259 non-null  str
 3   stop                 300259 non-null  object
 4   to                   300259 non-null  str
 5   price                300259 non-null  int64
 6   class                300259 non-null  str
 7   time_of_day          300259 non-null  str
 8   is_weekday           300259 non-null  int32
 9   month                300259 non-null  int32
 10  total_duration_mins  300259 non-null  int64
dtypes: datetime64[us](1), int32(2), int64(2), object(1), str(5)
memory usage: 36.0+ MB

In [41]:
df.to_csv("clean_data.csv",index=False)